
modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
[[mods]]
    modId = "kubejsarsnouveau"
    version = "${file.jarVersion}"
    displayName = "KubejsArsNoveau"
    authors = "BobVarioa"
    description = '''

    '''
[[dependencies.kubejsarsnouveau]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejsarsnouveau]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.20)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejsarsnouveau]]
    modId = "kubejs"
    mandatory = true
    versionRange = "[1902.6.1-build.282,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kubejsarsnouveau]]
    modId = "ars_nouveau"
    mandatory = true
    versionRange = "[3.12.3,)"
    ordering = "NONE"
    side = "BOTH"
